# Generated by Django 2.2.3 on 2019-07-21 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=250)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='R order total')),
                ('emailAddress', models.EmailField(blank=True, max_length=250, verbose_name='email Address')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('delivered_to', models.CharField(blank=True, max_length=250)),
                ('country', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(blank=True, max_length=250)),
                ('street_address', models.CharField(blank=True, max_length=250)),
                ('province', models.CharField(blank=True, max_length=250)),
                ('zip_code', models.CharField(blank=True, max_length=250)),
                ('phone_number', models.IntegerField(blank=True)),
                ('cash_or_card', models.CharField(blank=True, max_length=250, verbose_name='payment mode on delivery')),
            ],
            options={
                'db_table': 'Order',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='R Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'db_table': 'OrderItem',
            },
        ),
    ]
