# Generated by Django 2.2.3 on 2019-07-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivered_to',
            new_name='customer',
        ),
    ]
